runtime: nodejs12
service: frontend
instance_class: F1

default_expiration: "180d"

handlers:
- url: /static
  static_dir: frontend-dist/static
  secure: always
  expiration: "1h"

- url: /(.*\.(json|ico|js|txt|png))$
  static_files: frontend-dist/\1
  upload: frontend-dist/.*\.(json|ico|js|txt|png)$

- url: /.*
  static_files: frontend-dist/index.html
  upload: frontend-dist/index.html
  secure: always
  expiration: "1h"
